package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* s?bado 3 de abril de 2021 10H00' CST
*/

public interface CalculatorOperations 
{
  float plus (float a, float b);
  float minus (float a, float b);
  float times (float a, float b);
  float divide (float a, float b);
  float modul (float a, float b);
} // interface CalculatorOperations
